# GCP Profile Configuration for API Gateway

# Spring Cloud Eureka Registry - Private IPs of GCP VMs
eureka.client.serviceUrl.defaultZone=http://10.0.1.20:8761/eureka/,http://10.0.2.20:8761/eureka/
eureka.instance.prefer-ip-address=true
