server.port=8081
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

spring.data.mongodb.uri=mongodb://localhost:27017/bytebites_menu

app.upload.dir=${user.home}/eca-uploads/
app.upload.base-url=http://localhost:8080/api/menu/images/

# Disable GCP Datastore and Storage by default for local development
spring.cloud.gcp.datastore.enabled=false
spring.cloud.gcp.datastore.repositories.enabled=false
spring.cloud.gcp.storage.enabled=false
